[package]
name = "earthwyrm_bin"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DougLau/earthwyrm/earthwyrm_bin"
edition = "2018"

[dependencies]
argh = "0.1"
earthwyrm = "0.4"
env_logger = "0.7"
log = "0.4"
pointy = "0.3"
rosewood = "0.1"
