# earthwyrm.toml
#
# Socket address and port to bind server
bind_address = "127.0.0.1:3030"
# Root path for static files
document_root = "/var/lib/earthwyrm"
# Tile extent (within MVT files)
#tile_extent = 4096
# Tile pixels
#pixels = 256
# Buffer pixels around tile edges
buffer_pixels = 5
# Per-tile query limit
#query_limit = 1000
#
# Defining a table makes it available for layer rules
#   - name: Table name, as used in rules file
#   - db_table: Database table (may include schema)
#   - id_column: Database column to uniquely identify features
#   - geom_column: Database column for PostGIS feature geometry
#   - geom_type: Type of PostGIS geometry (polygon, linestring or point)
#
[[table]]
name = "polygon"
db_table = "planet_osm_polygon"
id_column = "osm_id"
geom_column = "way"
geom_type = "polygon"

[[table]]
name = "line"
db_table = "planet_osm_line"
id_column = "osm_id"
geom_column = "way"
geom_type = "linestring"

[[table]]
name = "roads"
db_table = "planet_osm_roads"
id_column = "osm_id"
geom_column = "way"
geom_type = "linestring"

[[table]]
name = "point"
db_table = "planet_osm_point"
id_column = "osm_id"
geom_column = "way"
geom_type = "point"
#
# Layer groups are collections of MVT files containing related layers.
#   - base_name: Base path name for URI
#   - rules_path: File containing layer rules
#
[[layer_group]]
base_name = "tile"
rules_path = "/etc/earthwyrm/tile.rules"
